### PR TITLE
Add M41L

### PR DESCRIPTION
**Pull request by brysondev**

### CODE REVIEW

**Comment by Rainyan** [comment]
Are we cleared in terms of copyright for adding this asset here directly?

**Comment by brysondev** [comment]
@blaberry Can you confirm?

**Comment by blaberry** [comment]
I'm confused, are these modified in any way from the base game? If not, we should not be rehosting them here. If yes, then okay, we needed to patch the ones from the base game, there's a clear need to host them.

**Comment by Rainyan** [comment]
> I'm confused, are these modified in any way from the base game? If not, we should not be rehosting them here. If yes, then okay, we needed to patch the ones from the base game, there's a clear need to host them.

The scoped variant of the gun was removed in a prior patch to the original game, so the assets no longer exist in the base game that we mount. So if we want to support it, we'd need to either have our own copy of the model files or figure out some other way of mounting it.

I suppose it's not strictly parity, as the gun doesn't exist in the current iteration of the game, but I can see why people might wanna have it as an option to play around with.

**Comment by brysondev** [comment]
> I'm confused, are these modified in any way from the base game? If not, we should not be rehosting them here. If yes, then okay, we needed to patch the ones from the base game, there's a clear need to host them. 

@kassibuss sent the files to me from an earlier build of OG and they work just fine. We have 2 PRs open for getting the code up to scratch.

**Comment by blaberry** [comment]
Thanks for the context, I'm giving the thumbs up to hosting them, we're working on getting the all clear in parallel.

**Comment by Agiel** [comment]
The script should be placed in the main repo imo. (And coincidentally, that's where the other scripts are).

**Comment by kassibuss** [comment]
> I'm confused, are these modified in any way from the base game? If not, we should not be rehosting them here. If yes, then okay, we needed to patch the ones from the base game, there's a clear need to host them.

The M41L uses the silenced mosok as a placeholder model in both OGNT and in rebuild, for reasons mentioned before. I probably should have asked beforehand if we should use the original models.

**Review by AdamTadeusz — APPROVED** [review]

**Review by Rainyan — APPROVED** [review]

**Pull request merged**
